### ISSUE TITLE
Extending using PartialType, OmitType… doesn't copy properties decorators

### ISSUE THREAD

**Issue by mlbonniec** [nestjs/mapped-types#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I've noticed that when extending a class (`Child`) from another (`Parent`), using `PartialType` (*for example, but this is the same with the other wrappers*) doesn't add the `Parent` properties decorators to the `Child`.

How did I notice this ? I've some swagger `@ApiProperty()` decorators in my `CreateDto`, and when extending the `UpdateDto extends PartialType(CreateDto) {}`, the `UpdateDto` doesn't have any properties in the Swagger.``

However, removing the `PartialType` wrapper "fix" the issue.

### Reproduction
https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter-2zmyjl

### Expected behavior

All the `Parent` properties decorators should be copied to the `Child`.

### Package version

2.0.2

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
If you're using swagger, then you should use `PartialType` from `@nestjs/swagger`, not `@nestjs/mapped-types`
