### ISSUE TITLE
Breaking change in 2.0.3 for override fields 

### ISSUE THREAD

**Issue by vsamofal** [nestjs/mapped-types#1224]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

c65d434c

### Versions

2.0.0 -> 2.0.3

### Describe the regression

sample entities hierarchy: 

```ts
abstract class BaseEntityHelper {
        @IsUUID()
        @Expose()
        id!: string | number;
        
        @Expose()
        anotherField!: string;
    }

    class SampleEntity extends BaseEntityHelper {

        @Expose()
        @IsUUID()
        override id!: string;

        @Expose()
        @IsString()
        name!: string;

    }

    class SampleEntityDto extends OmitType(SampleEntity, ['name'] as const) {

    }

```

So we have an abstract class with an id that can be a number or string overriding it and exposing it. Using omit type to create DTO, that has just a name field. 

Let's implement a simple test: 

```ts
it('instance to instance', () => {


            let sampleEntityWithoutId = new SampleEntity();

            sampleEntityWithoutId.id = 'just id';
            sampleEntityWithoutId.name = 'name';
            sampleEntityWithoutId.anotherField = 'anotherField';


            let dto = plainToInstance(SampleEntityDto, sampleEntityWithoutId, {
              excludeExtraneousValues: true,
              exposeDefaultValues: true,
              ignoreDecorators: true,
              exposeUnsetFields: false,
            });

            let justCopy = plainToInstance(SampleEntity, sampleEntityWithoutId, {
                excludeExtraneousValues: true,
                exposeDefaultValues: true,
                ignoreDecorators: true,
                exposeUnsetFields: false,
            });

            // this is failing but should be ok
            expect(dto.anotherField).toEqual('anotherField');
        })
```

The error is handled over here 
![image](https://github.com/nestjs/mapped-types/assets/27850115/d61806c2-ff39-4dd3-bb23-e671614f87d4)

but thrown over here 
![image](https://github.com/nestjs/mapped-types/assets/27850115/31854429-29ff-4241-95c0-9013ebc272d4)

this behavior recently changed, and it's a breaking change for this case at least. 

I'm ok to fix it by myself, just some comments from maintainers on expected behavior will be good to hear

as for me we should apply the most closest decorators or probably merge it somehow, but not sure is it that obvious to do the merge or no 

### Input code

provided

### Expected behavior

need suggestion

**Comment by vsamofal** [comment]
@KuanWenChen probably you can take a look, I understand that you were fixing something, but we also break some, so need to come up with some plan for all known cases to work

**Comment by KuanWenChen** [comment]
I thing problem is happen at value is not a iterable type. I am not sure why value is not a iterable type.
I thing this could fix it:
```typescript
[existingRules, targetMetadataEntries].forEach((entries) => {
  for (const [valueKey, value] of entries) {
    const arrayValue = Array.isArray(value) ? value : [value];
    if (mergeMap.has(valueKey)) {
      mergeMap.get(valueKey)!.push(...arrayValue);
    } else {
      mergeMap.set(valueKey, arrayValue);
    }
  }
});
```

**Comment by KuanWenChen** [comment]
maybe Array.isArray also could change to isIterable.
```typescript
function isIterable(obj: any) {
  // checks for null and undefined
  if (obj == null) {
    return false;
  }
  return typeof obj[Symbol.iterator] === 'function';
}
```

**Comment by kamilmysliwiec** [comment]
Could you create a PR for this issue?

**Comment by KuanWenChen** [comment]
OK, I think I found the problem.
[_excludeMetadatas, _exposeMetadatas, _typeMetadatas should not be a Array](https://github.com/typestack/class-transformer/blob/69cd8ccbc672179ea46492a625653ec448f03a17/src/MetadataStorage.ts#L11C1-L16C59)
So, they should be overwriten by children.
I would create PR as soon.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mapped-types/pull/1225
