### ISSUE TITLE
class-transformer dep update needed

### ISSUE THREAD

**Issue by devin-fee-ah** [nestjs/mapped-types#131]
https://github.com/nestjs/mapped-types/blob/master/package.json#L45

dev dependency is set properly, peer dependency is not. this will also have a downstream impact on `@nestjs/swagger`.

(here is the security notice: https://github.com/typestack/class-transformer/issues/339)

**Comment by voutasaurus** [comment]
Would this PR fix it: https://github.com/nestjs/mapped-types/pull/127

**Comment by devin-fee-ah** [comment]
Nah. We should drop the vulnerable one completely.

**Comment by kamilmysliwiec** [comment]
Published as 0.1.0
