### ISSUE TITLE
Mapped Types apparently remove @ApiProperty deklarations for swagger

### ISSUE THREAD

**Issue by Bellian** [nestjs/mapped-types#1534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a DTO defines @ApiProperty or @ApiPropertyOptional properties and another DTO is inferred using anny mapped types, the mapped fields do not show up in swagger.

```typescript
export class CreateOrganisationOptionDto {
    @ApiPropertyOptional()
    @ApiProperty({ description: 'The option ID' })
    @IsOptional()
    id: string;

    @ApiProperty({ description: 'The option name' })
    @IsString()
    option: string;

    @ApiProperty({ description: 'The option value' })
    value: JsonObject;
}
```

```typescript
export class UpdateOrganisationOptionDto extends OmitType(CreateOrganisationOptionDto, ['option']) {
    @ApiProperty({ description: 'The option value' })
    value: JsonObject;
}
```

Result:
![image](https://github.com/user-attachments/assets/593cc1d6-1cef-4b17-bc8b-9c11215c0b12)

### Minimum reproduction code

https://codesandbox.io/p/devbox/qmp437

### Steps to reproduce

1. navigate to: /api
2. have a look at the A / B Dto
  In BDto `id` is missing although only `option` is onited.
  Also changing to `PartialType` removes all annotations.

### Expected behavior

Swager definitions should be taken over from original DTO

### Package version

2.0.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
the `ApiPropertyOptional` is an alias to `ApiProperty` with `required:false`. Thus, you shouldn't be using both at same time.

**Comment by Bellian** [comment]
Thank you, but does not change anything regarding the problem.

**Comment by Bellian** [comment]
Oh I am so sorry! Just found out, that `@nestjs/swagger` comes with its own type-helpers: https://github.com/nestjs/swagger/tree/master/lib/type-helpers
