### ISSUE TITLE
RequiredType

### ISSUE THREAD

**Issue by mashkovtsev** [nestjs/mapped-types#55]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Details

Could you add RequiredType besides to PartialType that already exists, please?

Or whether any other variant with the type optional fields are created into with the same fields required.

**Comment by kamilmysliwiec** [comment]
I've looked into this one and this might not be doable tbh. Unfortunately, it's impossible to detect that the condition validation applied to a property = `@IsOptional`. Hence, the proposed `RequiredType` function would obviously mark all properties as required (in theory), but the "IsOptional" validation constraint wouldn't be ignored and so, not defining certain properties wouldn't lead to an error.
