### ISSUE TITLE
Create build using latest code

### ISSUE THREAD

**Issue by ccontour** [nestjs/mapped-types#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The code published to NPM does not correspond with github code, root package.json doesn't seem to be receiving version bumps to properly publish

- https://github.com/nestjs/mapped-types/blob/master/package.json#L3

### Minimum reproduction code

N/A

### Steps to reproduce

yarn add @nestjs/mapped-types

### Expected behavior

Installing this package should use the latest version. Bumping dependency versions in the package.json should at some point result in a build that can be pulled down and installed

### Package version

1.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

I am specifically attempting to resolve the class-transformer warnings I am getting while installing. The fix appears to already be in the code here, but I can't pull it in

**Comment by micalevisk** [comment]
I think this has something with your lockfile because

```bash
npm info @nestjs/mapped-types version
```

outputs `1.0.0`

**Comment by micalevisk** [comment]
try pinning the version `yarn add @nestjs/mapped-types@1.0.0`

**Comment by ccontour** [comment]
The content of that 1.0.0 is different from head in git if you go into the node_modules and look at the `package.json`. 

![2021-12-02_11-06](https://user-images.githubusercontent.com/35661840/144469153-2b278bd1-cc4f-4ce6-8209-658628726ff9.png)

It looks like the dependencies package file were updated, but the version was left at `1.0.0`. NPM should be rejecting those publishes with an error like `You cannot publish over the previously published versions: ###`. The version number must be incremented in order to publish properly

**Comment by micalevisk** [comment]
oh I had misunderstood that. You're right

![image](https://user-images.githubusercontent.com/13461315/144473946-2b43f01e-7827-46d3-adb9-4e9227402e87.png)
![image](https://user-images.githubusercontent.com/13461315/144473979-1ec18909-4abf-4f99-b8c7-241c103a0cec.png)

**Comment by kamilmysliwiec** [comment]
Fixed in 1.0.1
