### ISSUE TITLE
Can't inherit getter/setter and function

### ISSUE THREAD

**Issue by CodyTseng** [nestjs/mapped-types#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Can't inherit getter/setter and function.

```typescript
import { PickType } from "@nestjs/mapped-types";

class A {
  foo: number;

  bar: number;

  get baz() {
    return this.foo;
  }
}

class B extends PickType(A, ['foo', 'baz']) {}

const b = new B();
b.foo = 1;

console.log(b.baz); // undefined
```

### Minimum reproduction code

https://github.com/CodyTseng/example/blob/master/mapped-types/index.js

### Expected behavior

Can inherit getter/setter and function.

```typescript
import { PickType } from "@nestjs/mapped-types";

class A {
  foo: number;

  bar: number;

  get baz() {
    return this.foo;
  }
}

class B extends PickType(A, ['foo', 'baz']) {}

const b = new B();
b.foo = 1;

console.log(b.baz); // 1
```

### Package version

1.1.0

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hug0b** [comment]
I think it would be useful to preserve at least getters because it seems that it's not currently the case.

**Comment by CodyTseng** [comment]
> I think it would be useful to preserve at least getters because it seems that it's not currently the case.

I searched the previous issues and found that @kamilmysliwiec  explicitly said that this feature will not be added https://github.com/nestjs/mapped-types/issues/480, so I closed this issue 😭
