### ISSUE TITLE
PartialType can't work with class-validator

### ISSUE THREAD

**Issue by yodhcn** [nestjs/mapped-types#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

UpdateUserDto allow `{ name: null }` thereby giving validation issues
`QueryFailedError: SqliteError: NOT NULL constraint failed: user.name`

For ORM, null and undefined usually have different meanings
- `usersRepository.update({ name: null })` means update `user.name` to `null`
- `usersRepository.update({ name: undefined })` means don't update `user.name`

I think that PartialType should not use the `@IsOptional()` decorator, but should use `@ValidateIf((_object, value) => value !== undefined)`

### Minimum reproduction code

https://github.com/yodhcn/mapped-types-example

### Steps to reproduce

1. `npm i`
2. `npm start`
3.  POST http://localhost:3000/users { "name": "user_1",  "email": "user@gmail.com", "password": "12345678" }
4. PATCH http://localhost:3000/users { "name"; null }
5. see error `QueryFailedError: SqliteError: NOT NULL constraint failed: user.name`

### Expected behavior

UpdateUserDto should allow `{ name: undefined }`, but should not allow `{ name: null }`

### Package version

1.1.0

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
