### ISSUE TITLE
`IntersectionType` clause for more than 4 classes is not available in the npm version

### ISSUE THREAD

**Issue by marekbrainhub** [nestjs/mapped-types#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using `IntersectionType` on more than 4 classes produces a TypeScript error.

### Minimum reproduction code

n/a

### Steps to reproduce

```ts
class ClassA {}
class ClassB {}
class ClassC {}
class ClassD {}
class ClassE {}
IntersectionType(ClassA, ClassB, ClassC, ClassD, ClassE)
```

```
<snip>:10:50 - error TS2554: Expected 2-4 arguments, but got 5.

8  IntersectionType(ClassA, ClassB, ClassC, ClassD, ClassE)
                                                    ~~~~~~
```

### Expected behavior

TypeScript does not complain about more than four arguments.

### Package version

1.1.0

### Node.js version

18.7.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I suspect this is because the declaration file in the compiled library does not have the wildcard clause. I'm not sure if that is intended or if there is a workaround.

**Comment by micalevisk** [comment]
that's expected 

https://github.com/nestjs/mapped-types/blob/8c83b9262a35c6d42449e8584a57d8aa467a0218/lib/intersection-type.helper.ts#L9-L25

**Comment by jmcdo29** [comment]
We could add another level, or you could just nest the `IntersectionType` classes. `IntersectionType(ClassA, ClassB, IntersectionType(ClassC, ClassD), ClassE)` ad infinitum as necessary

**Comment by micalevisk** [comment]
indeed. That's sounds better to me. Otherwise someone may request another level again and again

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/mapped-types/issues/860#issuecomment-1255373205
