### ISSUE TITLE
Remove @nestjs/common dependency

### ISSUE THREAD

**Issue by Sylphide** [nestjs/mapped-types#907]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi,

I am currently trying to build a monorepo (using nrwl/nx) with both nestjs as a backend and nextjs as a frontend. My idea was to write DTOs in a single shared lib across my backend and frontend. The problem is that @nestjs/mapped-types uses @nestjs/common and I don't think it would be the best idea to have it has a dependency in my client side application. 

But since I am fairly new to this ecosystem I could be mistaken. Maybe since it is in a monorepo, the tree shaking that should occur during the build of my nextjs application would remove the unused dependencies? Or is it not that simple?

I still have the same problem with nestjs/swagger dependency which I use to decorate my DTOs, but I think I could work around it using the cli plugin but that's just another matter I guess.

### Describe the solution you'd like

Make @nestjs/mapped-types independent of @nestjs/common if possible

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

It would make using @nestjs/mapped-types possible on client side applications

**Comment by micalevisk** [comment]
looks like the only concrete class that we use from `@nestjs/common` is `Logger`.

https://github.com/nestjs/mapped-types/blob/2bb02845ede639f22bc4ef883997cb95a047542a/lib/type-helpers.utils.ts#L4

thus I don't see anything wrong on removing that dependency

**Comment by kamilmysliwiec** [comment]
You can configure webpack to dynamically resolve `@nestjs/common` to a different object/shim file, if needed.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
