### ISSUE TITLE
Could not resolve dependency: peerOptional class-validator@"^0.11.1 || ^0.12.0 || ^0.13.0" from @nestjs/mapped-types@1.2.0

### ISSUE THREAD

**Issue by mnrendra** [nestjs/mapped-types#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Unable to resolve dependency tree when installing `npm i @nestjs/mapped-types` using:  
- node: v18.12.1  
- nest: 9.1.5  
- class-validator: ^0.14.0  
<img width="723" alt="Screenshot 2022-12-11 at 11 44 32 PM" src="https://user-images.githubusercontent.com/7542440/206916917-8dc525ea-fea0-417b-8225-7cd5a452834e.png">

### Minimum reproduction code

https://github.com/mnrendra/iluvcoffee

### Steps to reproduce

1. `npm i class-validator class-transformer`  
2. `npm i @nestjs/mapped-types`  
3. See error:  
<img width="723" alt="Screenshot 2022-12-11 at 11 44 32 PM" src="https://user-images.githubusercontent.com/7542440/206917257-d9963210-5c9d-46d4-b2d6-ed450be44c81.png">

### Expected behavior

When intalling `npm i @nestjs/mapped-types` should be success with:  
"class-validator": "^0.14.0"

### Package version

1.2.0

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
that's because the range `^0.13.0` doens't match with the version `0.14.0` due to being under v0

To circumvent that you must use `class-validator@^0.13`

**Comment by DzixxxVizlib** [comment]
@kamilmysliwiec can U trigger renovate to update that dependency? pweaseeee ❤️

**Comment by Will956** [comment]
+1, we encounter that error because we're using `@nestjs/swagger` that uses `@nestjs/mapped-types`, full logs:
```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @nestjs/mapped-types@1.2.0
npm WARN Found: class-validator@0.14.0
npm WARN node_modules/class-validator
npm WARN   class-validator@"0.14.0" from the root project
npm WARN   2 more (@nestjs/common, @nestjs/swagger)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional class-validator@"^0.11.1 || ^0.12.0 || ^0.13.0" from @nestjs/mapped-types@1.2.0
npm WARN node_modules/@nestjs/mapped-types
npm WARN   @nestjs/mapped-types@"1.2.0" from @nestjs/swagger@6.1.4
npm WARN   node_modules/@nestjs/swagger
npm WARN 
npm WARN Conflicting peer dependency: class-validator@0.13.2
npm WARN node_modules/class-validator
npm WARN   peerOptional class-validator@"^0.11.1 || ^0.12.0 || ^0.13.0" from @nestjs/mapped-types@1.2.0
npm WARN   node_modules/@nestjs/mapped-types
npm WARN     @nestjs/mapped-types@"1.2.0" from @nestjs/swagger@6.1.4
npm WARN     node_modules/@nestjs/swagger
```
please 🙏

**Comment by Rosevear-AB** [comment]
Running into the same issue when trying to use the PartialType function via the NEST CLI resource generator (it uses the PartialType to help create the update DTO for the resource).
