### ISSUE TITLE
Install fails when class-validtor 0.14.0 already installed

### ISSUE THREAD

**Issue by wijkjh** [nestjs/mapped-types#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

First install class-validator: `npm install class-validator`. This will install currently version 0.14.0
Afterwards install mapped-types: `npm install @nestjs/mapped-types`

This fails with a npm error unable to resolve dependency tree.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: iluvcoffee@0.0.1
npm ERR! Found: class-validator@0.14.0
npm ERR! node_modules/class-validator
npm ERR!   class-validator@"^0.14.0" from the root project
npm ERR!   peerOptional class-validator@"*" from @nestjs/common@9.2.1
npm ERR!   node_modules/@nestjs/common
npm ERR!     @nestjs/common@"^9.0.0" from the root project
npm ERR!     peer @nestjs/common@"^7.0.8 || ^8.0.0 || ^9.0.0" from @nestjs/mapped-types@1.2.0
npm ERR!     node_modules/@nestjs/mapped-types
npm ERR!       @nestjs/mapped-types@"^1.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional class-validator@"^0.11.1 || ^0.12.0 || ^0.13.0" from @nestjs/mapped-types@1.2.0
npm ERR! node_modules/@nestjs/mapped-types
npm ERR!   @nestjs/mapped-types@"^1.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Just following your NestJS course.
Added some random nestjs example public repo in which it also occurs.

### Minimum reproduction code

https://github.com/hantsy/nestjs-rest-sample

### Steps to reproduce

1. `npm i class-validator`
2. `npm i @nestjs/mapped-types`

### Expected behavior

Should install without errors.

### Package version

1.2.0

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
this should be fixed by #930

---

For now you could use `npm i class-validator@0.13.0`
