### ISSUE TITLE
Update security dependencies 

### ISSUE THREAD

**Issue by andlo779** [nestjs/mapped-types#957]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This repo has an hardcoded dependency to "class-validator:0.13.2" which is flagged as security risk. I can't update my project as this dependency breaks the update. 

### Describe the solution you'd like

Update the dependency to version "0.14.0".

### Teachability, documentation, adoption, migration strategy

NA

### What is the motivation / use case for changing the behavior?

So I can update my project to no include dependencies that are flagged as security risks.

**Comment by andlo779** [comment]
Just found a pull-request for this issue: https://github.com/nestjs/mapped-types/pull/945

**Comment by GeekyGeeky** [comment]
@andlo779 @caucik @valorkin 
Can this be attended to?

**Comment by micalevisk** [comment]
please read this: https://github.com/nestjs/mapped-types/pull/949#issuecomment-1383056801

**Comment by andlo779** [comment]
Thanks. This information somehow managed to slip me by.
