### ISSUE TITLE
Update the class-validator dependency to 0.14.0

### ISSUE THREAD

**Issue by tkglaser** [nestjs/mapped-types#966]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Raising this for visibility. There is a critical vulnerability in `class-validator` which is resolved in `0.14.0`.

### Describe the solution you'd like

Please update the packages dependency and peerDependency of `class-validator` to `0.14.0` only.

### Teachability, documentation, adoption, migration strategy

There is an automated PR open: #930. It has been open for some time, can we please merge it? Many people are urgently waiting for this.

### What is the motivation / use case for changing the behavior?

Critical security vulnerability.

**Comment by jmcdo29** [comment]
https://github.com/nestjs/mapped-types/pull/949#issuecomment-1383056801
